apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
      tolerations:
      - key: "AppName"
        operator: "Equal"
        value: "ts_performance_test"
        effect: "NoExecute"
        tolerationSeconds: 3600
#  AppName=ts_performance_test:NoExecute